Repository apache/maven-site, pull requests merged in 2025-02, with the labels that each got.

#629 [MNGSITE-521] Copy edit and clarify artifacts.md
  content/markdown/repositories/artifacts.md
Labels: documentation

#670 Drop invalid combine.self
  pom.xml
Labels: bug

#676 Use Smetana for generating puml, fix comments syntax
  src/plantuml/maven-sources/core.puml
  src/plantuml/maven-sources/doxia.puml
  src/plantuml/maven-sources/misc.puml
  src/plantuml/maven-sources/plexus.puml
  src/plantuml/maven-sources/plugins.puml
  src/plantuml/maven-sources/shared.puml
  src/plantuml/maven-sources/site.puml
  src/plantuml/multi-subproject.puml
Labels: maintenance

#673 Add empty .mvn directory - avoid warning on Maven 4
  .mvn/keep-me
Labels: maintenance

#674 Install graphviz - dot utility
  .github/workflows/verify-site.yml
Labels: enhancement

#675 Add support for 4.x suffix in doc helper
  content/markdown/developers/website/component-reference-documentation-helper.md
Labels: enhancement

#685 Remove not existed staging repo
  pom.xml
Labels: bug

#686 Update site descriptor to 2.0
  content/site.xml
Labels: enhancement

#682 Add steps about milestones and release notes on GitHub to release procedure
  content/apt/developers/release/maven-project-release-procedure.apt
Labels: enhancement

#690 Add Stale action
  .github/workflows/stale.yml
Labels: enhancement

#691 Add info about automated actions on GitHub
  content/markdown/developers/conventions/github.md
Labels: enhancement

#699 Small update of retirement page
  content/apt/developers/retirement-plan-plugins.apt
Labels: documentation

#701 Add info about EOL to release history.
  content/markdown/docs/history.md.vm
Labels: documentation

#703 Hint about release drafter during vote
  content/apt/developers/release/maven-project-release-procedure.apt
Labels: documentation

#704 more compact display, drop now obsolete plugin compat
  content/markdown/docs/history.md.vm
Labels: documentation

#697 Add Maven archetype article and talk to the resources and videos
  content/markdown/articles.md
Labels: documentation

#705 Remove the cover column in video table
  content/markdown/articles.md
Labels: maintenance

#598 [MNGSITE-550] What's new in Maven 4?
  content/markdown/whatsnewinmaven4.md
  content/site.xml
Labels: enhancement
