Repository apache/maven-site, pull requests merged in 2025-01, with the labels that each got.

#599 Enable GitHub issues
  .asf.yaml
  .github/ISSUE_TEMPLATE/BUG.yml
  .github/ISSUE_TEMPLATE/IMPROVEMENT.yml
  .github/ISSUE_TEMPLATE/config.yml
  README.md
  pom.xml
Labels: enhancement

#626 Require Java 17
  pom.xml
Labels: maintenance

#625 Update support and training page to use local images
  content/markdown/support-and-training.md
  content/resources/images/logos/logo_infosupport.svg
  content/resources/images/logos/logo_takari.png
  content/resources/images/logos/logo_vogella.png
  content/resources/images/logos/logo_webagesolutions.svg
Labels: maintenance, documentation

#621 Convert xdoc (without parsing) to Markdown
  content/markdown/articles.md
  content/markdown/developers/mojo-api-specification.md
  content/markdown/repository/index.md
  content/markdown/repository/maven-central-repository.odg
  content/markdown/repository/maven-repositories.odg
  content/markdown/scm.md
  content/xdoc/articles.xml
  content/xdoc/developers/mojo-api-specification.xml
  content/xdoc/repository/index.xml
  content/xdoc/scm.xml
Labels: maintenance, documentation

#614 [MNGSITE-504] Fix rendering / markdown warnings
  content/apt/archives/maven-2.x/maven-2.1-architectural-goals.apt
  content/markdown/faq-unoffical.md
  content/xdoc/download.xml.vm
  content/xdoc/errors/404.xml.vm
Labels: maintenance, documentation

#636 Housekeeping on SCM Site
  content/markdown/scm.md
Labels: documentation

#641 GitHub issues - release vote
  content/apt/developers/release/maven-project-release-procedure.apt
Labels: maintenance

#647 Edit guide to java-plugin development for clarity
  content/apt/guides/plugin/guide-java-plugin-development.apt.vm
Labels: documentation

#649 More articles and videos
  content/markdown/articles.md
Labels: documentation

#645 Update and shorten central repository guide
  content/apt/repository/guide-central-repository-upload.apt
  content/markdown/project-roles.md
Labels: documentation
