Repository apache/maven-site, pull requests merged in 2025-03, with the labels that each got.

#695 Clarify types, extensions, and classifiers
  content/markdown/repositories/artifacts.md
Labels: documentation

#709 [MNGSITE-463] Update Maven Logging page
  content/markdown/maven-logging.md
Labels: documentation

#716 [MPDF-113] Retire PDF Plugin
  content/apt/plugins/index.apt
  content/markdown/scm.md
  src/plantuml/maven-sources/plugins.puml
Labels: maintenance

#718 Jira to GitHub issues - fluido skin
  content/apt/skins/index.apt
  content/markdown/scm.md
Labels: maintenance

#721 Use jenkins workspace as site cache
  Jenkinsfile
Labels: enhancement

#717 Small additions to retirement plan
  content/apt/developers/retirement-plan-plugins.apt
  content/apt/developers/website/deploy-component-reference-documentation.apt
  content/markdown/developers/website/component-reference-documentation-helper.md
Labels: documentation

#724 Add link to Maven 4.0.0-rc3 announcement
  content/markdown/docs/history.md.vm
Labels: bug

#722 [MNGSITE-439] Other ways to install
  content/markdown/install.md.vm
  content/site.xml
Labels: documentation

#727 Update articles about plugin execution configuration
  content/apt/guides/introduction/introduction-to-the-lifecycle.apt
  content/apt/guides/mini/guide-configuring-plugins.apt
  content/apt/pom.apt.vm
Labels: documentation

#738 Improve display of quote
  content/markdown/whatsnewinmaven4.md
Labels: documentation

#745 Github issues WAR-plugin
  content/apt/plugins/index.apt
  content/markdown/scm.md
Labels: maintenance

#744 Github issues EAR-plugin
  content/apt/plugins/index.apt
  content/markdown/scm.md
Labels: maintenance
